FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY ./metrics/requirements_embedding.txt /app

RUN pip install --no-cache-dir -r requirements_embedding.txt 

COPY ./metrics/embedding_metric.py /app

EXPOSE 8000

CMD ["uvicorn", "embedding_metric:app", "--host", "0.0.0.0", "--port", "8000"]