route:
  repeat_interval: 15s # Time interval between consecutive notifications for the same alert
  receiver: discord

receivers:
- name: discord
  discord_configs:
  - webhook_url: https://discord.com/api/webhooks/1401261214755061801/yfCqkNZcrh3TYTugbPY4RlbGP1fQu5ON3-u5_D3a4rQr0bIUcYGEKXX-P59q0VezCeCL