replicaCount: 2

image:
  repository: hoangkimkhanh1907/embedding-service
  tag: 0.0.15
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  name: embedding-service
  httpPort:
    enable: true
    port: 80
    targetPort: 5000

resources:
  limits:
    cpu: "500m"
    memory: "1Gi"
  requests:
    cpu: "250m"
    memory: "512Mi"