replicaCount: 2

image:
  repository: hoangkimkhanh1907/embedding-service
  tag: 0.0.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  name: embedding-service
  httpPort:
    enable: true
    port: 80
    targetPort: 5000

resources:
  limits:
    cpu: "1000m"
    memory: "2Gi"
  requests:
    cpu: "500m"
    memory: "1Gi"